version: 2.1

orbs:
  orb-tools: circleci/orb-tools@8.3.0
  prettier: cfra/prettier@dev:@@orb-revision@@

x-aliases:
  filter-only-special-tag: &filter-only-special-tag
    filters:
      branches:
        ignore:
          - /.*/
      tags:
        only:
          - /(test-|release-).*/

jobs:
  do-succeed:
    executor: orb-tools/ci-base
    steps:
      - checkout
      - run:
          name: Wait
          command: sleep 23
      - run:
          name: Succeed
          command: exit 0

workflows:
  integration-workflow:
    jobs:
      - do-succeed:
          <<: *filter-only-special-tag
