version: 2.1

orbs:
  orb-tools: circleci/orb-tools@8.3.0
  prettier: cfra/prettier@dev:@@orb-revision@@

x-aliases:
  filter-only-special-tag: &filter-only-special-tag
    filters:
      branches:
        ignore:
          - /.*/
      tags:
        only:
          - /(test-|release-).*/

workflows:
  integration-workflow:
    jobs:
      - prettier/check:
          <<: *filter-only-special-tag
