version: 2.1

orbs:
  orb-tools: circleci/orb-tools@8.3.0
  prettier: cfra/prettier@dev:@@orb-revision@@

x-aliases:
  filter-only-stage2-tag: &filter-only-stage2-tag
    filters:
      branches:
        ignore:
          - /.*/
      tags:
        only:
          - /(test-|release-).*/
  filter-only-release-tag: &filter-only-release-tag
    filters:
      branches:
        ignore:
          - /.*/
      tags:
        only:
          - /release-.*/

workflows:
  integration-workflow:
    jobs:
      - prettier/check:
          <<: *filter-only-stage2-tag
      - orb-tools/pack:
          requires:
            - prettier/check
          <<: *filter-only-release-tag
      - orb-tools/publish:
          requires:
            - orb-tools/pack
          attach-workspace: yes
          checkout: no
          orb-ref: cfra/prettier@${CIRCLE_TAG:8}
          <<: *filter-only-release-tag
